# Approve Pull Request
#
# Automatically approve a pull request when a review is requested from @flexdevelopment by certain
# users.
#
#
# References:
#
# - https://cli.github.com/manual/gh_pr_review
# - https://docs.github.com/actions/using-workflows/events-that-trigger-workflows#pull_request

---
name: approve-pr
on:
  pull_request:
    types:
      - review_requested
permissions:
  pull-requests: write
env:
  GITHUB_TOKEN: ${{ secrets.PAT_REPO_ADMIN }}
jobs:
  approve-pr:
    if: github.event.requested_reviewer == 'flexdevelopment'
    runs-on: ubuntu-latest
    steps:
      - id: approve
        name: Approve pull request
        if: github.actor == 'unicornware'
        run: gh pr review ${{ github.event.number }} --approve --body 'lgtm 👍🏾'
