# Continuous Integration
#
# References:
#
# - https://docs.github.com/actions/using-workflows/events-that-trigger-workflows#pull_request
# - https://docs.github.com/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
# - https://github.com/actions/checkout
# - https://github.com/actions/setup-node

---
name: continuous-integration
on:
  pull_request:
  workflow_dispatch:
permissions:
  packages: read
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  HUSKY: 0
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REF: ${{ github.head_ref || github.ref_name }}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16.16.0]
    steps:
      - id: checkout
        name: Checkout ${{ env.REF }}
        uses: actions/checkout@v3.0.2
        with:
          persist-credentials: false
          ref: ${{ env.REF }}
      - id: setup-node
        name: Use node v${{ matrix.node }}
        uses: actions/setup-node@v3.4.1
        with:
          cache: yarn
          cache-dependency-path: yarn.lock
          node-version: ${{ matrix.node }}
      - id: yarn
        name: Install dependencies
        if: github.actor != 'dependabot[bot]'
        run: yarn
      - id: yarn-dependabot
        name: Install dependencies for dependabot
        if: github.actor == 'dependabot[bot]'
        run: yarn --no-immutable
      - id: format
        name: Check code formatting
        run: yarn check:format
      - id: lint
        name: Check lint status
        run: yarn check:lint
      - id: spelling
        name: Check spelling
        run: yarn check:spelling
      - id: test
        name: Run tests
        run: yarn test
        env:
          NODE_ENV: test
          NODE_NO_WARNINGS: 1
          NODE_OPTIONS: --es-module-specifier-resolution=node
          TS_NODE_PROJECT: ./tsconfig.tsnode.json
      - id: pack
        name: Pack project
        run: yarn pack -o %s-%v.tgz
        env:
          NODE_ENV: production
          NODE_NO_WARNINGS: 1
          NODE_OPTIONS: --es-module-specifier-resolution=node
