# Label Syncer
#
# References:
#
# - https://github.com/micnncim/action-label-syncer

---
name: label-syncer
on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - id: sync
        name: Sync labels
        uses: micnncim/action-label-syncer@v1.3.0
        with:
          manifest: .github/labels.yml
