# Release
#
# Publish GitHub release when a `release/*` branch pull request is approved or on workflow dispatch.
#
# References:
#
# - https://cli.github.com/manual/gh_pr_merge
# - https://cli.github.com/manual/gh_release_create
# - https://docs.github.com/actions/using-workflows/events-that-trigger-workflows#pull_request_review
# - https://docs.github.com/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
# - https://docs.github.com/actions/using-workflows/using-github-cli-in-workflows
# - https://github.com/actions/checkout
# - https://github.com/actions/github-script
# - https://github.com/actions/setup-node
# - https://github.com/bdougie/close-issues-based-on-label
# - https://github.com/octokit/graphql-action

---
name: release
on:
  pull_request_review:
    branches:
      - release/*
    types:
      - submitted
  workflow_dispatch:
    inputs:
      pr:
        description: pull request number
        required: true
      ref:
        description: full commit sha
        required: true
      version:
        description: project version
        required: true
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REF: ${{ github.event.inputs.ref || github.event.pull_request.head.ref }}
jobs:
  metadata:
    name: Metadata
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    outputs:
      artifact-path: ${{ steps.artifact.outputs.result }}
      prerelease: ${{ steps.prerelease.outputs.result }}
      tag: ${{ steps.version.outputs.tag }}
      version: ${{ steps.version.outputs.version }}
    steps:
      - id: checkout
        name: Checkout main
        uses: actions/checkout@v3.0.2
        with:
          ref: main
      - id: version
        name: Get version and tag
        uses: actions/github-script@v6.1.0
        with:
          script: |
            const { inputs, pull_request } = context.payload

            let version

            if (pull_request) {
              version = pull_request.head.ref.split('release/')[1]
            }

            if (inputs) version = inputs.version

            core.setOutput('tag', version)
            core.setOutput('version', version)
      - id: artifact
        name: Get artifact path
        uses: actions/github-script@v6.1.0
        env:
          VERSION: ${{ steps.version.outputs.version }}
        with:
          result-encoding: string
          script: |
            const workspace = `@${context.payload.repository.full_name}`
            const version = process.env.VERSION

            return `./${workspace.replace('/', '-')}-${version}.tgz`
      - id: dist-tag
        name: Get dist tag
        uses: ./
        with:
          target: ${{ steps.version.outputs.version }}
      - id: prerelease
        name: Check for prerelease
        uses: actions/github-script@v6.1.0
        env:
          DIST_TAG: ${{ steps.dist-tag.outputs.tag }}
        with:
          # todo: calculate number of prereleases to include in release notes
          script: return !!process.env.DIST_TAG
  publish:
    name: Publish GitHub release
    needs: metadata
    runs-on: ubuntu-latest
    environment:
      name: production
      url:
        ${{ github.server_url }}/${{ github.repository }}/releases/tag/${{
        needs.metadata.outputs.tag }}
    env:
      NOTES_FILE: ./RELEASE_NOTES.md
      TAG: ${{ needs.metadata.outputs.tag }}
    strategy:
      matrix:
        node: [16.16.0]
    steps:
      - id: checkout
        name: Checkout ${{ env.REF }}
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
          ref: ${{ env.REF }}
      - id: setup-node
        name: Use node v${{ matrix.node }}
        uses: actions/setup-node@v3.4.1
        with:
          node-version: ${{ matrix.node }}
      - id: yarn
        name: Install dependencies
        run: yarn
        env:
          HUSKY: 0
          NODE_AUTH_TOKEN: ${{ env.GITHUB_TOKEN }}
      - id: pack
        name: Pack project
        run: yarn pack -o %s-%v.tgz
        env:
          NODE_ENV: production
          NODE_NO_WARNINGS: 1
          NODE_OPTIONS: --es-module-specifier-resolution=node
      - id: release-notes
        name: Generate release notes
        # todo: handle prereleases
        run: yarn conventional-changelog -o $NOTES_FILE
        env:
          TS_NODE_PROJECT: ./tsconfig.tsnode.json
      - id: tag
        name: Create annotated tag
        uses: actions/github-script@v6.1.0
        with:
          script: |
            const endpoint = '/repos/{owner}/{repo}/git/commits/{commit_sha}'

            const commit = await github.request(`GET ${endpoint}`, {
              ...context.repo,
              commit_sha: process.env.GITHUB_SHA
            })

            const tag = await github.rest.git.createTag({
              ...context.repo,
              message: commit.message,
              object: commit.sha,
              tag: process.env.TAG,
              tagger: commit.committer,
              type: 'commit'
            })

            await github.rest.git.createRef({
              ...context.repo,
              ref: `refs/tags/${process.env.TAG}`,
              sha: tag.data.sha
            })
      - id: publish
        name: Publish release
        run: gh release create $TAG $ASSET -t=$TAG -F=$NOTES_FILE -p=$PRERELEASE
        env:
          ASSET: ${{ needs.metadata.outputs.artifact-path }}
          PRERELEASE: ${{ needs.metadata.outputs.prerelease }}
  cleanup:
    name: Cleanup
    needs: [metadata, publish]
    runs-on: ubuntu-latest
    env:
      PR: ${{ github.event.inputs.pr || github.event.number }}
    steps:
      - id: checkout
        name: Checkout ${{ env.REF }}
        uses: actions/checkout@v3.0.2
        with:
          ref: ${{ env.REF }}
      - id: linked-issues
        name: Query linked issues
        uses: octokit/graphql-action@v2.2.22
        with:
          query: |
            query (
              $owner: String!,
              $repo: String!,
              $pr: Int!,
              $limit: Int = 20
            ) {
              repository(owner: $owner, name: $repo) {
                pullRequest(number: $pr) {
                  closingIssuesReferences(
                    first: $limit
                    orderBy: { direction: ASC, field: CREATED_AT }
                  ) {
                    edges {
                      node {
                        number
                      }
                    }
                  }
                }
              }
            }
          owner: ${{ github.repository_owner }}
          pr: ${{ env.PR }}
          repo: ${{ github.event.repository.name }}
      - id: label-linked-issues
        name: Add status:released label to linked issues
        uses: actions/github-script@v6.1.0
        env:
          DATA: ${{ steps.linked-issues.outputs.data }}
        with:
          script: |
            const { pullRequest } = JSON.parse(process.env.DATA).repository
            const { edges } = pullRequest.closingIssuesReferences

            const issues = edges.map(edge => edge.node.number)

            for (const issue_number of issues) {
              await github.rest.issues.addLabels({
                ...context.repo,
                issue_number,
                labels: ['status:released']
              })
            }
      - id: close-released-issues
        name: Close issues with status:released label
        uses: bdougie/close-issues-based-on-label@master
        env:
          LABEL: status:released
      - id: enable-auto-merge
        name: Enable auto-merge
        if: github.event_name != 'workflow_dispatch'
        run: gh pr merge $PR --auto --delete-branch --squash
